/// <reference types="@figma/plugin-typings" />
import { PLUGIN_DATA_KEY, type MainToUiMessage, type UiToMainMessage } from "./messages.js";

/**
 * Figma adapter. This file knows nothing about icon rules: it receives a
 * rendered SVG plus metadata from the UI and turns it into a native component.
 */

figma.showUI(__html__, { width: 380, height: 640, themeColors: true });

function post(message: MainToUiMessage): void {
  figma.ui.postMessage(message);
}

function componentName(style: string, name: string): string {
  return `icon/${style}/${name}`;
}

async function createComponentFromSvg(msg: Extract<UiToMainMessage, { type: "create-component" }>): Promise<ComponentNode> {
  const frame = figma.createNodeFromSvg(msg.svg);
  const component = figma.createComponent();
  component.name = componentName(msg.style, msg.name);
  component.resizeWithoutConstraints(msg.canvas, msg.canvas);
  component.description = `${msg.language.name} v${msg.language.version} · ${msg.style} · generated by Icon Foundry`;
  component.setPluginData(PLUGIN_DATA_KEY, msg.spec);

  for (const child of [...frame.children]) {
    component.appendChild(child);
  }
  frame.remove();

  const { x, y } = figma.viewport.center;
  component.x = Math.round(x - msg.canvas / 2);
  component.y = Math.round(y - msg.canvas / 2);
  figma.currentPage.appendChild(component);
  return component;
}

figma.ui.onmessage = async (msg: UiToMainMessage) => {
  switch (msg.type) {
    case "cancel":
      figma.closePlugin();
      return;
    case "create-component": {
      try {
        const component = await createComponentFromSvg(msg);
        figma.currentPage.selection = [component];
        figma.viewport.scrollAndZoomIntoView([component]);
        figma.notify(`Created ${component.name}`);
        post({ type: "component-created", nodeName: component.name });
      } catch (error) {
        const message = error instanceof Error ? error.message : String(error);
        figma.notify(`Icon Foundry: ${message}`, { error: true });
        post({ type: "error", message });
      }
      return;
    }
  }
};
